name: deploy
on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server-dir: ${{ secrets.DEST }}
          server: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          dry-run: true
