name: deploy
on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git-ftp push
        uses: sebastianpopp/git-ftp-action@fix-ssl-issue
        with:
          url: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          options: --auto-init --insecure