name: deploy
on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy via ssh
        uses: garygrossgarten/github-action-scp@v0.6.0
        with:
            local: /
            remote: ${{ secrets.DEST }}
            host: ${{ secrets.HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.PASSWORD }}
