name: deploy
on:
  push:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.HOST }}
          ftp-username: ${{ secrets.SSH_USER }}
          ftp-password: ${{ secrets.PASSWORD }}
          git-ftp-args: --insecure --dry-run 