name: validate and deploy
on:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate charity.json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schemas/charity-schema.json
          INPUT_JSONS: /charity.json
      - name: Validate lokality.json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /schemas/lokality-schema.json
          INPUT_JSONS: /lokality.json
      
  upload:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: git-ftp push
        uses: sebastianpopp/git-ftp-action@fix-ssl-issue
        with:
          url: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          options: --auto-init --insecure --force
  send-email-on-success:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail Action
        id: sendmail
        uses: vineetchoudhary/mailgun-action@v1.1
        with:
          api-key: ${{ secrets.MAILGUN_API_SECRET }}
          domain: ${{ secrets.MAILGUN_DOMAIN }}
          from: ${{ secrets.FROM }}
          to: ${{ secrets.RECIPIENT }}
          cc: test@example.com
          subject: Změny nahrány do mapy TKS
          body: Ahoj, změny od {{ GITHUB_ACTOR }} jsou nyní k vidění na webu http://tks.dchhk.cz/.<br /><br /><i>Tento e-mail je generovaný automaticky.</i>
      - name: Send Mail Action Response
        run: echo "${{ steps.sendmail.outputs.response }}"
